### PR TITLE
Add 345tool.com

### PR DESCRIPTION
**Pull request by MarkoCen**

### CODE REVIEW

**Comment by stefanjudis** [comment]
Hello @MarkoCen, thanks so much for contributing.

I came across 345tool.com before and I'm a little undecided if the root of all the great tools should be added to tiny helpers. Every added tiny helper includes a description and links to a tool for solving one problem. If we include the root of 345tool.com people we can't provide a meaningful description and visitors don't know what they can find on 345tool.

There's so many tools in there that I'm not sure if we should add all one-by-one, either.

What are your thoughts?

**Comment by MarkoCen** [comment]
Hi @stefanjudis 

Thanks for the feedback! Agree with your concern, do you think I can submit multiple times for different tools on 345tool? If not, I can change the PR to only include the most popular tool on the website.

**Comment by stefanjudis** [comment]
@MarkoCen 

Thanks for understanding.

> do you think I can submit multiple times for different tools on 345tool?

Sure, go for it!

**Comment by stefanjudis** [comment]
Closing due to inactivity. :)

**Pull request closed without merging**
