### PR TITLE
Adds https://faicons.dev/

### PR DESCRIPTION
**Pull request by r-i-c-h**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focused on a single, development related issue.
- [X] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
That's great Rich! Thank you for contributing. Do you mind removing `Typography`? I'm happy to merge then. :)

**Comment by stefanjudis** [comment]
Thanks. :)

**Comment by ParaBolt** [comment]
Hey, don't you think "Favicons" is not the correct tag here?

**Comment by stefanjudis** [comment]
You're right. :) Missed that. Will update, when I have a minute. :)

**Comment by stefanjudis** [comment]
https://github.com/stefanjudis/tiny-helpers/commit/46d6470d0648d1dd00ffbf0a2eb564676c16ec9a

**Pull request merged**
