### PR TITLE
Correcting missing tag

### PR DESCRIPTION
**Pull request by fili**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focused on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
Thanks. 

Hmm... I don't think the `API` tag is the right tag. 

Usually, I'm not accepting APIs unless they have a free UI component. And the `API` tag is more about tiny helpers that help to work with APIs. I don't think that's true for this case. :) 

I'm gonna close this one. Feel free to reopen.

**Comment by fili** [comment]
Thanks, not sure if I understand though. The page linked has both a search form (to query the API though the web interface) and all the documentation on how to access the API using REST, and both entry points are freely accessible without any restrictions.

**Comment by stefanjudis** [comment]
> And the API tag is more about tiny helpers that help to work with APIs. I don't think that's true for this case.

It's not a helper to work with APIs. :)

**Comment by fili** [comment]
Fair enough :) Thanks!

**Pull request closed without merging**
