### PR TITLE
Add Chmod Calculator

### PR DESCRIPTION
**Pull request by OnurGvnc**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focussed on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
@OnurGvnc That's cool! Thank you so much for contributing.

Could you do me a favor and match the desired format for `desc`?

> the desc field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

And also add the tag `System administration`? Happy to merge after. :)

**Comment by stefanjudis** [comment]
@OnurGvnc Looks like you're adding more than one tool per PR. :)

It'd be great to follow the convention though. 🙈

> you only add one (!) new helper per pull request.

**Comment by OnurGvnc** [comment]
@stefanjudis Whoops.. I'm sorry I did it by mistake. I got it back. 

> Could you do me a favor and match the desired format for desc?

"Convert Linux file permissions between different formats"
is it ok?

**Comment by stefanjudis** [comment]
Jup. Sounds good. :)

**Comment by stefanjudis** [comment]
Thank you so much!

**Comment by OnurGvnc** [comment]
@stefanjudis Thanks Stefan!
This is a very useful project! 🏆

**Pull request merged**
