### PR TITLE
Add sortjson.com

### PR DESCRIPTION
**Pull request by bennycode**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focused on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
Nice one! Thanks @bennycode 🙇‍♂️

**Comment by bennycode** [comment]
Hey @stefanjudis, has this helper been removed? I cannot find it anymore. 🥲

**Comment by stefanjudis** [comment]
Hmm... Don't know. I remove some dead ones every now and then. But happy to take it back. :)

**Comment by stefanjudis** [comment]
[d9bab298965c72887973d86eb8901f23b7074e35 ](https://github.com/stefanjudis/tiny-helpers/commit/d9bab298965c72887973d86eb8901f23b7074e35) :)

**Comment by stefanjudis** [comment]
Sure thing. :) 🫡

**Pull request merged**
