### PR TITLE
Add Subtle Patterns

### PR DESCRIPTION
**Pull request by ParaBolt**
Oh hey, back with another pattern site which Transparent Textures is based off on.

### CODE REVIEW

**Comment by ParaBolt** [comment]
Hey, any updates?

**Comment by stefanjudis** [comment]
@ParaBolt Heyo, thank you for submitting and sorry for the delay. 🙈

I think this helper is def useful. The reason why I'm uncertain is that this PR marks it as `CSS` helper and there is no CSS export or something. Also, most of these background patterns could be done way smaller in SVG.

What do you think about these two points?

**Comment by ParaBolt** [comment]
Hi, yeah even I am unsure about how to tag them as. I could not find any suitable tag, should I tag as "Misc" instead?

True, some of the simpler patterns could be recreated as SVG but I don't think other patterns like Fabric or Grunge could be done that way. Also since they are seamless, they can be used as tileable backgrounds as well (similar to TransparentTextures, hence the CSS tag).

**Comment by stefanjudis** [comment]
Ja I feel like `misc` would be a better choice, because there is no CSS reference. :) Mind updating? :)

**Comment by ParaBolt** [comment]
Thanks for the guidance, have updated the pull request!

**Comment by stefanjudis** [comment]
Thanks! :)

**Pull request merged**
