### PR TITLE
Add spring-editor

### PR DESCRIPTION
**Pull request by pomber**

### CODE REVIEW

**Comment by stefanjudis** [comment]
@pomber That looks fancy! But tbh I'm not quite sure what I see in front of me. 😊

**Comment by pomber** [comment]
Haha, maybe it's a bit niche.

It's similar to https://cubic-bezier.com/ but for spring based animations (things like react-motion, react-spring, framer motion).

It helps you pick the parameters for the spring.

**Comment by stefanjudis** [comment]
Interesting! I'm a bit hesitant about merging because I'm not sure people will understand, tbh. :/

Maybe adding an animating element like cubic-bezier has and adding some explanation to the tool could help? What do you think?

**Comment by stefanjudis** [comment]
@pomber They Rodrigo, we discussed your addition and decided that it's a cool tool but without further explanation, it's hard for people to get it (an explanation could help as mentioned in the prev comment). For now, I'm gonna close this PR. Happy to re-evaluate in the future. :)

**Pull request closed without merging**
