### PR TITLE
Add font-flipper

### PR DESCRIPTION
**Pull request by innocenzi**
Added [Font Flipper](https://fontflipper.com/upload). I often use it and thought it was in the scope of this project. :)

- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focused on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

### CODE REVIEW

**Comment by stefanjudis** [comment]
@hawezo This is great, it's unusable in Firefox though (which makes me a little hesitant). :/ Do you by chance know who's maintaining this?

**Comment by hawezo** [comment]
Mmh, is it? Just tried on Firefox 75.0 and it works perfectly, no lag or anything. 

That said I don't know the maintainer, and I'd understand if you didn't want to add this tool if it doesn't work for you. I've just found it really useful so I wanted to share, the decision is up to you now ^^

**Comment by stefanjudis** [comment]
Hmm... FF 75 on a Mac has no icons for me which makes it unusable. It works for you?

Screenshot 2020-05-05 at 12 34 03

**Comment by hawezo** [comment]
It does work for me on FF 75, I'm on Windows. But what icons are you referring to?

**Comment by stefanjudis** [comment]
You're right. Thank you! :)

**Pull request merged**
