### PR TITLE
Add svg icon a11y fixer

### PR DESCRIPTION
**Pull request by clottman**
I don't know why the other helpers got reordered - I only ran the `helper:add` script and committed. 

## How to add a new helper

**Please only add one (!) new helper per pull request.** This will speed up the review and merge process.

### What does not count as a tiny helper?

- while APIs are very helpful we decided to not include them
- npm modules are out of scope per defintion of tiny-helpers
- learning sites that have a purely educational purpose

### Formatting of tiny helpers

Your helper JSON files have to follow these criterias:

---

- [ ] `desc` includes an "actionable sentence"

✅ DO: "Create something great" or "Transform something into something else"

❌ DON'T: "ABC is a tool that can something great"

---

- [ ] `maintainers` includes an a human being (and not companies)

✅ DO: individualA,individualB

❌ DON'T: companyA

---

To sum it up – your JSON addition should look as follows:

```json
{
  "name": "A new helper",
  "desc": "Add a new helper to tiny-helpers.dev",
  "url": "https://some.url",
  "tags": ["Misc"],
  "maintainers": ["PersonA"],
  "addedAt": "2020-01-17"
}
```

### CODE REVIEW

**Comment by stefanjudis** [comment]
Thanks so much for contributing. @clottman 

> I don't know why the other helpers got reordered - I only ran the helper:add script and committed.

Yeah, we'll get rid of these issues very soon. :) 

Quick question: how experimental is the tool? I just tried on SVG and it broke it completely. :/ 

I tried this Chromium logo:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   version="1.1"
   width="256"
   height="256"
   id="svg3039"
   inkscape:version="0.47 r22583"
   sodipodi:docname="Chromium_11_Logo.svg">
  <sodipodi:namedview
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1"
     objecttolerance="10"
     gridtolerance="10"
     guidetolerance="10"
     inkscape:pageopacity="0"
     inkscape:pageshadow="2"
     inkscape:window-width="1280"
     inkscape:window-height="750"
     id="namedview6"
     showgrid="false"
     inkscape:zoom="1.4142136"
     inkscape:cx="372.87473"
     inkscape:cy="103.791"
     inkscape:window-x="-8"
     inkscape:window-y="-8"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg3039" />
  <metadata
     id="metadata3045">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title />
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs
     id="defs3043">
    <linearGradient
       id="linearGradient3803">
      <stop
         style="stop-color:#d7def0;stop-opacity:1;"
         offset="0"
         id="stop3805" />
      <stop
         id="stop3811"
         offset="0.5"
         style="stop-color:#ffffff;stop-opacity:1" />
      <stop
         style="stop-color:#d5def0;stop-opacity:1"
         offset="1"
         id="stop3807" />
    </linearGradient>
    <linearGradient
       id="linearGradient3776"
       inkscape:collect="always">
      <stop
         id="stop3778"
         offset="0"
         style="stop-color:#b2cde9;stop-opacity:1" />
      <stop
         id="stop3780"
         offset="1"
         style="stop-color:#c4dbee;stop-opacity:1" />
    </linearGradient>
    <linearGradient
       id="linearGradient3750">
      <stop
         id="stop3752"
         offset="0"
         style="stop-color:#d0e2f1;stop-opacity:1" />
      <stop
         style="stop-color:#cadef0;stop-opacity:1"
         offset="0.85580856"
         id="stop3756" />
      <stop
         id="stop3754"
         offset="1"
         style="stop-color:#95bee3;stop-opacity:1" />
    </linearGradient>
    <linearGradient
       id="linearGradient3708">
      <stop
         style="stop-color:#658db6;stop-opacity:1"
         offset="0"
         id="stop3710" />
      <stop
         id="stop3716"
         offset="0.76777935"
         style="stop-color:#527fab;stop-opacity:1;" />
      <stop
         style="stop-color:#4071a0;stop-opacity:1"
         offset="1"
         id="stop3712" />
    </linearGradient>
    <linearGradient
       id="linearGradient3698">
      <stop
         style="stop-color:#96d0e1;stop-opacity:1"
         offset="0"
         id="stop3700" />
      <stop
         id="stop3706"
         offset="0.67819428"
         style="stop-color:#89b7e1;stop-opacity:1" />
      <stop
         style="stop-color:#699dd3;stop-opacity:1"
         offset="1"
         id="stop3702" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       id="linearGradient3647">
      <stop
         style="stop-color:#3b79bc;stop-opacity:1;"
         offset="0"
         id="stop3649" />
      <stop
         style="stop-color:#94b8e0;stop-opacity:1"
         offset="1"
         id="stop3651" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       id="linearGradient3588">
      <stop
         style="stop-color:#ffffff;stop-opacity:1"
         offset="0"
         id="stop3590" />
      <stop
         style="stop-color:#000000;stop-opacity:0;"
         offset="1"
         id="stop3592" />
    </linearGradient>
    <radialGradient
       inkscape:collect="always"
       xlink:href="#linearGradient3588"
       id="radialGradient3594"
       cx="-118.77966"
       cy="121.49152"
       fx="-118.77966"
       fy="121.49152"
       r="25.491526"
       gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(0.02177942,-0.95743591,0.97872327,0.02221687,-235.0993,5.0684454)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient3647"
       id="linearGradient3653"
       x1="-397.81323"
       y1="149.18764"
       x2="-397.55933"
       y2="51.355946"
       gradientUnits="userSpaceOnUse" />
    <radialGradient
       inkscape:collect="always"
       xlink:href="#linearGradient3698"
       id="radialGradient3704"
       cx="-383.2746"
       cy="217.91029"
       fx="-383.2746"
       fy="217.91029"
       r="59.401995"
       gradientTransform="matrix(-1.2861568,-0.08596317,0.11453678,-1.7136762,-425.01982,469.50099)"
       gradientUnits="userSpaceOnUse" />
    <radialGradient
       inkscape:collect="always"
       xlink:href="#linearGradient3708"
       id="radialGradient3714"
       cx="-123.5"
       cy="-11.570732"
       fx="-123.5"
       fy="-11.570732"
       r="95.627118"
       gradientTransform="matrix(-0.00756512,0.55751399,-1.0314585,-0.01398286,113.23967,103.212)"
       gradientUnits="userSpaceOnUse" />
    <radialGradient
       inkscape:collect="always"
       xlink:href="#linearGradient3750"
       id="radialGradient3748"
       cx="-94.87291"
       cy="165.27281"
       fx="-94.87291"
       fy="165.27281"
       r="60.481357"
       gradientTransform="matrix(0.81293878,1.6998003,-2.1519091,1.0291615,564.39485,118.47915)"
       gradientUnits="userSpaceOnUse" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient3776"
       id="linearGradient3774"
       x1="162.07127"
       y1="85.239708"
       x2="220.76114"
       y2="78.875748"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(3.3917128,7.418629)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient3803"
       id="linearGradient3809"
       x1="-382.04123"
       y1="37.280548"
       x2="-381.39438"
       y2="165.56691"
       gradientUnits="userSpaceOnUse" />
  </defs>
  <path
     sodipodi:type="arc"
     style="fill:url(#radialGradient3594);fill-opacity:1;fill-rule:nonzero;stroke:none"
     id="path2814"
     sodipodi:cx="-118.23729"
     sodipodi:cy="122.57627"
     sodipodi:rx="25.491526"
     sodipodi:ry="25.491526"
     d="m -92.745764,122.57627 a 25.491526,25.491526 0 1 1 -50.983056,0 25.491526,25.491526 0 1 1 50.983056,0 z"
     transform="matrix(4.680851,0,0,4.7978723,685.10478,-449.69946)" />
  <path
     style="fill:url(#linearGradient3774);fill-opacity:1;fill-rule:nonzero;stroke:none"
     d="m 232.17258,88.120422 c 0,15.673918 -19.79135,34.931518 -45.84395,34.931518 -26.0526,0 -59.92241,-16.08123 -59.92241,-31.755152 0,-15.673924 21.11981,-28.38015 47.17241,-28.38015 19.90254,0 46.36122,18.293224 56.45971,20.3521 0.79179,1.710571 1.36862,2.925087 2.13424,4.851684 z"
     id="path3655"
     sodipodi:nodetypes="cssscc" />
  <path
     style="fill:#2e5c91;fill-opacity:1;fill-rule:nonzero;stroke:none"
     d="m 38.822019,65.971523 c 12.38148,-9.610993 35.314514,-1.245318 51.289554,19.334679 15.975027,20.579998 17.694937,51.065068 5.31349,60.676058 -12.38147,9.61099 -34.17571,-5.29155 -50.15074,-25.87156 -12.20392,-15.72181 -4.05062,-41.19089 -8.61646,-50.430553 0.61589,-1.122052 1.381696,-2.456607 2.164156,-3.708624 z"
     id="path3655-4-8"
     sodipodi:nodetypes="cssscc" />
  <path
     style="fill:url(#radialGradient3714);fill-opacity:1;fill-rule:nonzero;stroke:none"
     d="m 230.04347,83.261765 c -7.0081,-0.03265 -61.07025,0.289575 -107.66568,0.0654 -17.371,5.108098 -31.704627,13.258827 -39.181777,29.154945 -5.33639,-4.54237 -40.74576,-42.215609 -44.40678,-46.440684 31.38983,-41.648805 74.528017,-45.559321 82.915257,-45.559321 8.38724,0 70.64407,-8.631855 108.33898,62.77966 z"
     id="path3596"
     sodipodi:nodetypes="ccccsc" />
  <path
     style="fill:#699dd3;fill-opacity:1;fill-rule:nonzero;stroke:none"
     d="m 117.12454,243.96815 c -12.49835,-9.45851 -14.5752,-36.93927 1.14635,-57.71356 15.72155,-20.77428 41.03582,-34.94753 53.53417,-25.48904 12.49834,9.4585 7.44792,38.96701 -8.27364,59.74129 -12.01027,15.87024 -35.4911,16.88498 -43.22681,23.69505 -1.23894,-0.0455 -1.95523,-0.0605 -3.18007,-0.23374 z"
     id="path3655-4"
     sodipodi:nodetypes="cssscc" />
  <path
     style="fill:url(#radialGradient3748);fill-opacity:1;fill-rule:nonzero;stroke:none"
     d="m 120.3032,244.20103 c 3.58354,-6.02268 28.85859,-52.8991 52.69131,-92.9389 4.41104,-17.56095 5.34663,-33.64185 -4.5584,-48.14993 6.62173,-2.29412 58.23852,-13.976353 63.73684,-14.987686 19.9656,48.180076 1.44992,87.338276 -2.80522,94.565966 -4.25515,7.22768 -28.40179,65.25666 -109.06453,61.51055 z"
     id="path3596-1"
     sodipodi:nodetypes="ccccsc" />
  <path
     style="fill:url(#radialGradient3704);fill-opacity:1;fill-rule:nonzero;stroke:none"
     d="m 36.696853,69.642524 c 3.46858,6.089612 30.72312,52.780196 53.77852,93.272576 13.094367,12.50527 27.684997,19.48512 45.191737,18.03328 -1.2738,6.89113 -16.62898,57.75037 -18.4638,63.03126 -51.756237,-6.42158 -76.669777,-41.85476 -80.854757,-49.1233 -4.18497,-7.26855 -42.7297502,-56.91452 0.3483,-125.213816 z"
     id="path3596-1-7"
     sodipodi:nodetypes="ccccsc" />
  <path
     transform="matrix(0.77294737,0,0,0.77619098,435.90647,53.275706)"
     style="fill:url(#linearGradient3653);fill-opacity:1;stroke:url(#linearGradient3809);stroke-width:10.07013607;stroke-miterlimit:4;stroke-opacity:1"
     d="m -338.44068,101.42373 c 0,32.65032 -26.46832,59.11864 -59.11865,59.11864 -32.65032,0 -59.11864,-26.46832 -59.11864,-59.11864 0,-32.650327 26.46832,-59.118646 59.11864,-59.118646 32.65033,0 59.11865,26.468319 59.11865,59.118646 z"
     id="path3645" />
  <path
     style="fill:#ffffff;fill-opacity:1;fill-rule:nonzero;stroke:none"
     d="m 163.54619,108.89582 c 18.52979,17.09836 16.03302,29.55794 10.0625,44 -3.10892,-22.25001 -2.34478,-32.42697 -10.0625,-44 z"
     id="rect3782"
     sodipodi:nodetypes="ccc" />
  <path
     style="fill:#ffffff;fill-opacity:1;fill-rule:nonzero;stroke:none"
     d="m 101.42092,173.63924 c -22.645593,-14.47335 -29.809884,-45.71983 -8.813354,-62.99032 -10.847561,19.77514 -6.225429,32.39863 8.813354,62.99032 z"
     id="rect3782-4"
     sodipodi:nodetypes="ccc" />
</svg>

```

**Comment by clottman** [comment]
Huh! I'm not sure, really. It's worked for me in the past, but is also breaking for me on the code you shared.

**Comment by clottman** [comment]
@stefanjudis I talked to the maintainer and they updated so that you will see a warning message now that IDs were important to the SVG and so were not removed, and a suggested workaround for if the icon will be used multiple times on the page. 

screenshot of running the added tool on the sample code provided by stefanjudis

**Comment by stefanjudis** [comment]
Wooohooooo! That's great thank you. I'll have another try asap.

**Comment by stefanjudis** [comment]
Thx. :)

**Pull request merged**
