### PR TITLE
add remixicon

### PR DESCRIPTION
**Pull request by ccampean**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [ ] you only add one (!) new helper per pull request.
- [ ] you have checked if an open PR already exists.
- [ ] the submitted website is focussed on a single, development related issue.
- [ ] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
@ccampean Thank you. That's def cool and useful. 🎉

Could you do me a favor and fix the `desc` field and remove the space from one of the maintainers?

> the desc field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you.

**Comment by ccampean** [comment]
> 
> 
> @ccampean Thank you. That's def cool and useful. 🎉
> 
> Could you do me a favor and fix the `desc` field and remove the space from one of the maintainers?
> 
> > the desc field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").
> 
> Thank you.

For the `desc` field is it ok, if I fill it with `Neutral-style system symbols` ?

**Comment by ccampean** [comment]
@stefanjudis Just corrected both fields.

**Comment by stefanjudis** [comment]
Thank you! 🎉

**Pull request merged**
