### PR TITLE
Add dither it to helpers

### PR DESCRIPTION
**Pull request by alexharris**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR please make sure that to have a look at the [CONTRIBUTING.md](../CONTRIBUTING.md). :)

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by fhemberger** [comment]
Looks cool, thank you!

**Comment by alexharris** [comment]
Thanks for making tiny helpers. One note, it seems like the "performance"
tag got removed from Dither it! Not a big deal to me, but maybe there is a
bug in the process somewhere?

**Comment by fhemberger** [comment]
Indeed, that's odd … 🤔

/cc @stefanjudis

**Comment by stefanjudis** [comment]
Whoops... no clue what I did there. let's pretend it didn't happen okay. :D

**Comment by alexharris** [comment]
😂

**Pull request merged**
