### PR TITLE
Add Image BG Blurer

### PR DESCRIPTION
**Pull request by denno020**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [*] you only add one (!) new helper per pull request.
- [*] you have checked if an open PR already exists.
- [*] the submitted website is focused on a single, development related issue.
- [*] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
@denno020 Thanks for contributing to TH.

I just tried it but it didn't seem to work in FF or Chrome. The downloaded images wasn't blurred or anything. :/

grafik

**Comment by denno020** [comment]
That's odd, I was using it heaps today..

Does that image have a transparent background? Or is it all white? If it's
all white, and if it's the same aspect ratio as the preview, then the
actual image is likely blocking the blur

**Comment by stefanjudis** [comment]
Here's the image. :) 

notion-image

**Comment by denno020** [comment]
I replied to the email and unfortunately the images that I attached to that email didn't come through with my message..

Here they are now:

307264269-fffffa7c-6b2b-4e03-b2d5-ebf21ca88973-removebg-preview
cropped

**Comment by stefanjudis** [comment]
Alright. I think I see what's going on. I just tried another image.

grafik

I kinda works but I think it's hard to use. Could we add an easy way to add vertical / horizontal padding to the image? I would expect people will be as confused as I am. 

So I'd propose upload an image and to sliders that allow me to see the outer spacing which will include the blurred effect.

WDYT? :)

**Comment by denno020** [comment]
Thanks for the feedback mate! There is an aspect ratio button in the top right of each preview that can be used to change the dimensions of the image that is generated, which I believe will achieve the same outcome as having sliders.

I'm pretty happy with the UI as it is. It's certainly not the prettiest, but I've found it to be pretty functional and haven't actually had anyone indicating they're getting confused, so keen to keep it as is.

If that's a blocker for Tiny Helpers, then I thank you for considering my little app for your directory :)

**Comment by stefanjudis** [comment]
Alright. Then thanks for considering TH. :) 

I've to be a little more gate keeper'ish these days and I think I'm gonna pass for now. 

Thanks for understanding. :)

**Pull request closed without merging**
