### PR TITLE
Jwt.io/#debugger.io

### PR DESCRIPTION
**Pull request by D10221**
Would you add "Jwt.io/#debugger.io" the list ? 
Thanks!

### CODE REVIEW

**Comment by stefanjudis** [comment]
@D10221 Nice one! 🙇‍♂️

Could we maybe change `code` to `JavaScript`? What do you think?

**Comment by D10221** [comment]
> 
> 
> @D10221 Nice one! 🙇‍♂️
> 
> Could we maybe change `code` to `JavaScript`? What do you think?

100% ! .. a i simply selected from the list :)

**Comment by stefanjudis** [comment]
Sweet! I'll take it! Thanks a bunch!

May take a while until it's live... hitting several rate limits here. 🙈

**Comment by D10221** [comment]
Thanks to you for putting this list up ! 
🍺  Cheers!

**Pull request merged**
