### PR TITLE
Add 'FB ID Finder' to helpers.json

### PR DESCRIPTION
**Pull request by elharony**
If you want to get FB ID from Facebook Page/Profile/Group URL. Then, **[FindFB.id](https://findfb.id/)** will definitely save your time when integrating Facebook with 3rd-Party Services, trying to fetch certain info from Facebook Account using its FB ID, not the username.

### Example
[Docusaurus.io](https://docusaurus.io/) requires `authorFBID` when writing a blog post

### CODE REVIEW

**Comment by elharony** [comment]
Hey @stefanjudis ,
Do you need any further action from me to merge it?

**Comment by stefanjudis** [comment]
@elharony It's all good. I'll come to it eventually. :) There are just 38 other PRs open right now. :)

**Comment by stefanjudis** [comment]
@elharony It's all good. I'll come to it eventually. :) There are just 38 other PRs open right now. :)

**Comment by elharony** [comment]
Perfect 💯 
I would love to contribute to this project. How can I help you, @stefanjudis ?

**Comment by stefanjudis** [comment]
> I would love to contribute to this project. How can I help you, @stefanjudis ?

You can always have a look at the open issues. :)

**Comment by fhemberger** [comment]
Thank you, merged!

**Comment by elharony** [comment]
Thanks, @fhemberger ! 👍

**Pull request merged**
