### PR TITLE
Add CyberChef

### PR DESCRIPTION
**Pull request by dickwyn**

### CODE REVIEW

**Comment by stefanjudis** [comment]
Thanks @dickwyn. 🙇‍♂️ I see you didn't pick a tag. Do you have an idea what tag would fit? I'm up for adding more if needed. :)

**Comment by dickwyn** [comment]
@stefanjudis Whoops, missed that. Let me go ahead and adds some tags

**Comment by dickwyn** [comment]
@stefanjudis Updated with tags 🙌

**Comment by fhemberger** [comment]
Hi, thank you for your PR!

However, at this point I'm reluctant to merge it: The site describes itself as _"swiss army knife"_, presenting **a lot** of different tools, but for tiny helpers we are looking for _single-purpose_ online tools. It should be clear from its description what specific problem this website solves, and I think in this case the offer is not focussed enough.

**Pull request closed without merging**
