### PR TITLE
add Color contrast checker

### PR DESCRIPTION
**Pull request by Kilian**
- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focussed on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

I built a really fast color contrast checker that suggests better colors if the contrast ratio is not sufficient. Supports both AA and AAA levels. https://polypane.app/color-contrast/

### CODE REVIEW

**Comment by Kilian** [comment]
Can I rejig @now with anything other than a commit?

**Comment by Ryuno-Ki** [comment]
> Zeit check failed with „Need authorization to deploy”.

**Comment by stefanjudis** [comment]
Yeah, I messed something up here. Will have a look soon. I'm currently onboarding a new job and everything's a little busy. :)

**Comment by stefanjudis** [comment]
Thanks! 🎉

**Pull request merged**
