### PR TITLE
Add helper: Elastic Reality

### PR DESCRIPTION
**Pull request by jikkuatwork**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [ ] you only add one (!) new helper per pull request.
- [ ] you have checked if an open PR already exists.
- [ ] the submitted website is focused on a single, development related issue.
- [ ] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
@jikkuatwork Thanks — that's pretty fancy. :) But what do I with this morph animation. It's a canvas element and there's no export button. Do I miss anything?

**Comment by jikkuatwork** [comment]
Yes, I am planning to add an export button. Somehow a few of my attempts
didn't work well. So, I thought of just launching and seeing if
someone will find it useful.

--
Jikku Jose
Co-founder, StoryBrain <https://storybrain.com>

**Comment by stefanjudis** [comment]
I'm not sure when I'd use it, but I'd be open to adding it to TH if it has an export button. :)

**Comment by jikkuatwork** [comment]
Oh cool, okay.

**Comment by stefanjudis** [comment]
I'll close here for now not to have another hanging PR. :) Feel free to ping me once there's an export. :)

**Comment by jikkuatwork** [comment]
Sure, will create an export. Also, I would like to add another in the meantime, I suppose that won't be possible unless I do the export, since the PR looks connected?

**Comment by stefanjudis** [comment]
Another tool? Then please open another PR. :) happy to have a look at it.

**Comment by jikkuatwork** [comment]
Already pushed. I am not sure about this workflow, will I be able to do a
new PR with jus that commit?

--
Jikku Jose
Co-founder, StoryBrain <https://storybrain.com>

**Comment by jikkuatwork** [comment]
Awesome, thank you so much! Sent the PR
--
Jikku Jose
Co-founder, StoryBrain <https://storybrain.com>

**Pull request closed without merging**
