### PR TITLE
Added softwium, a regex visualizer

### PR DESCRIPTION
**Pull request by cyrilbois**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focused on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
@cyrilbois Thanks for contributing to tiny helpers. Maybe I'm mistaken, but is this visualizer working correctly?

image

I can't see a visualization. 🤔

**Comment by cyrilbois** [comment]
Hello @stefanjudis, that's strange, it's supposed to work on Opera / Edge and Chrome(119).
Sorry to bother you, but which version are you using? Thank you.

**Comment by stefanjudis** [comment]
@cyrilbois Hmm. Now it works. I remember I saw an JS exception, though. 🤷‍♂️

I made a tiny adjustment and looks good now! Thanks for contributing. 😊

**Comment by cyrilbois** [comment]
Thank you

**Pull request merged**
