### PR TITLE
Add temp-mail.io

### PR DESCRIPTION
**Pull request by kernel-picnic**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focused on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
Thanks @kernel-picnic and welcome to TH. :) 

Could you check the PR description (you ticked it but didn't follow).

> the desc field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

**Comment by kernel-picnic** [comment]
@stefanjudis you're welcome) Sorry, I misunderstood a bit - changed text

**Comment by stefanjudis** [comment]
Thanks!

**Comment by kernel-picnic** [comment]
Thank you! 🙂

**Pull request merged**
