### PR TITLE
[meta] Conflict free file format

### PR DESCRIPTION
**Pull request by akx**
This PR mainly splits up `helpers.json` to multiple files under `helpers/` and changes tooling to make that possible (since reading those files is now async).

Things seem to work and look the same :)

### CODE REVIEW

**Comment by stefanjudis** [comment]
This is great! Thank you @akx!

I'll have a look at it over the weekend, okay? Just had a quick look and it looks reasonable. 

And also I think I'd then delay the merge a little bit until I made it through all the open PRs to not force all the people to change their PRs. Does that sound reasonable?

But anyways, good stuff! 👍

**Comment by akx** [comment]
> And also I think I'd then delay the merge a little bit until I made it through all the open PRs to not force all the people to change their PRs. Does that sound reasonable?

Absolutely. That's why I left the `scripts/explode-helpers.js` script in the tree, so it can be used to transform possible future contributions. :)

Just ping me when everything's merged and I can rebase this and reapply the script :)

**Comment by stefanjudis** [comment]
@akx Love it! Great collab! Thank you!

> Just ping me when everything's merged and I can rebase this and reapply the script :)

Can only take weeks, PR's are still rolling in. Can only take weeks. 🙈

**Comment by akx** [comment]
> Can only take weeks, PR's are still rolling in. Can only take weeks. 🙈

Well, PRs _will_ keep rolling in (some of which will inevitably also have merge conflicts in the helpers.json file).

Here's an idea: I can edit this PR so

* helpers.json isn't deleted yet
* it's used as base data on top of which the data from individual files is merged

That way new contributors would create new `helpers/something.json` files, but currently open PRs aren't disturbed either.

Then when all current PRs targeting the monolithic helpers.json are done with, we can run the script again and get rid of the monolithic file.

How's that sound?

**Comment by stefanjudis** [comment]
Sounds lovely! 👍

**Comment by akx** [comment]
> Sounds lovely! 👍

Changes made! The revised code will read `helpers.json` first, then overlay the individual files on top of it.

**Comment by stefanjudis** [comment]
I'll have a look tmrw during the day. :) Thanks Aarni!!!

**Comment by stefanjudis** [comment]
Alright. :) Let's do it. I had a look at it and tested it – it worked fine! :) Thanks a bunch Aarni!

**Pull request merged**
