### PR TITLE
Add SVGeez helper

### PR DESCRIPTION
**Pull request by nikitahl**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [ ] you only add one (!) new helper per pull request.
- [ ] you have checked if an open PR already exists.
- [ ] the submitted website is focussed on a single, development related issue.
- [ ] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
@nikitahl Thanks Nikita for contributing.

Could you do me a favor and adjust the `desc` field?

> the desc field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

**Comment by nikitahl** [comment]
@stefanjudis Strange, I've already done that:
`"desc": "SVG background pattern generator",`
https://github.com/stefanjudis/tiny-helpers/pull/193/files#diff-d21bd86fe501daa3085e807ff396becfR3
Is it something I'm missing?

**Comment by stefanjudis** [comment]
@nikitahl Thank you! I'll take it! 🎉

Should the action item be clearer somehow?

**Comment by nikitahl** [comment]
No, it's fine, I guess I was just being a slowpoke.

**Pull request merged**
