### PR TITLE
Add helper: Pastely

### PR DESCRIPTION
**Pull request by jikkuatwork**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focused on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
@jikkuatwork Thanks for contributing!  🎉

I'd like to propose some minor improvements before potentially bringing it onto TH.

I was very confused initially. 😅 When I opened the app I've read the word "paste" and pressed `CMD+V` which didn't do anything. This puzzled me. Then I clicked "paste" and it opened a `paste` dialog. This workflow felt hard for me on a laptop.

I would have expected (and preferred) an input field or that the site just let's me paste. 😅
 
grafik

Then I accidentally added two links and I couldn't find a way to remove one link again. 

grafik

I'll close here (to keep the number of opne PRs low) I'm up for considering adding the helper, when the minor UX issues are tackled. :) Feel free to ping me again and thanks a ton for contributing to TH!

**Comment by jikkuatwork** [comment]
@stefanjudis thanks for the feedback. The tool is essentially a helper for phones, it gives you are super fast way to collect links. - - Its a PWA for phones
- The decision to avoid input box is on purpose, there is no meddling with getting focus and pasting. Its a single button.
- But I hear you about adding shortcut for desktop to paste
- The dialog is a security policy by browsers to get permission
- If you click the arrow you will get an action sheet with a number of option including clearing the entire data.
- The system also generates a unique url that you can share with multiple devices so that one place you can add and another device you can get those links
- This has worked for me very well when I was researching a ton of links across social media, sharing with others and working on it. Thought this might be useful for someone.

**Comment by stefanjudis** [comment]
Thanks for giving more context. :) I think I discovered all the functionality. For considering adding, I still think it should have some improvements:

- there needs to be some explanation for people opening it — having a "paste" button is not enough imo 😉
- the desktop experience doesn't feel quite right
- you can't edit or remove single links

> This has worked for me very well when I was researching a ton of links across social media, sharing with others and working on it. Thought this might be useful for someone.

That's great. :)

**Comment by jikkuatwork** [comment]
Thanks for quick explanation. But, will adding ctrl+v short cut for desktop make it acceptable?

Adding explanation is anti-thesis to my vision of the product as its free, no-signup and super easy to figure out. Once its figured after 1/2 minutes it becomes so natural. Its minimal on purpose and a lot of thought was put into to to avoid every elements thats unwanted to be removed.

So, I am not sure about adding explanation.

Edit/Delete is also against the concept. Its function is to just keep pasting whatever you find so that you get like a quick note slip that you can use it your other machine, so edit or similar interactions aren't something thats there. Its so minimal like a small piece of paper, you get what you write, no option to undo or edit. Because its precisely like a remote clipboard between devices.

**Comment by jikkuatwork** [comment]
Totally. I was just wondering if adding the short cut would cut it. (Sorry for explaining beyond that.)

And you misquoted me, this is the fill version: "Adding explanation is anti-thesis to my vision of the product as its free, no-signup and super easy to figure out. "

I am not expecting your reply but I am responding because you took time to reply. Adding no explanation is not because its free. Its because its super easy to figure out. There is only two buttons in the page. And the title of the main button is exactly what it does. I mentioned free and no signups because, experimenting to find what it is practically zero effort. Infact I would argue easier than reading explanation. 

But its okay, if you don't want to include it. I respect your decision. Its your list.

**Comment by stefanjudis** [comment]
Then we agree to disagree. :) Case closed.

**Pull request closed without merging**
