### PR TITLE
Add SVGcode

### PR DESCRIPTION
**Pull request by tomayac**
Please only merge this after the official launch (will ping you).

# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [X] you only add one (!) new helper per pull request.
- [X] you have checked if an open PR already exists.
- [X] the submitted website is focused on a single, development related issue.
- [X] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by tomayac** [comment]
This is now ready to go public: https://twitter.com/ChromiumDev/status/1461781609699581966. Thanks for Tiny Helpers!

**Comment by tomayac** [comment]
CC: @stefanjudis

**Comment by stefanjudis** [comment]
Let's ship it then. 🤷‍♂️ Thanks Thomas!

**Comment by tomayac** [comment]
Thanks, and sorry for bringing this up on a Friday evening.

**Comment by stefanjudis** [comment]
Haha, no worries. :) It's on me to read emails on Friday. 🙈

**Pull request merged**
