### PR TITLE
Create Calendar Icons Generator helper entry

### PR DESCRIPTION
**Pull request by denno020**
# Thank you for opening a pull request to tiny-helpers.dev ❤️

Before you submit your PR, please take a look at the [contributing guidelines](https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md). :)

To make it easier for us to review and merge your PR, please make sure …

- [x] you only add one (!) new helper per pull request.
- [x] you have checked if an open PR already exists.
- [x] the submitted website is focused on a single, development related issue.
- [x] the `desc` field includes an "actionable sentence" (e.g. "Create something great" or "Transform something into something else").

Thank you! 🙇‍♂️

### CODE REVIEW

**Comment by denno020** [comment]
Apologies for the extra commits that are associated with this PR - I was hoping they would disappear when I hit the Create Pull Request button, as my previous tiny helper has already been merged, but at least those changes don't appear in the Diff panel

**Comment by stefanjudis** [comment]
Holy! Does this helper generate all days? :D That's kinda cool. Can you do me a favor and only go with the `Misc` tag? I'm happy to take it then.

And don't worry about the commits, it'll be squashed anyways. :)

**Comment by denno020** [comment]
All done! Thanks Stefan.

Oh and yes, one for every day of the year :)

**Comment by stefanjudis** [comment]
Thanks!

**Pull request merged**
